//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LogCollector.cpp
//  @ Date : 2020/1/7
//  @ Author :
//
//

#include "LogCollector.h"

LogCollector::LogCollector() : logSubscriber(nullptr, "!@#$%")
{
    defaultCategoryName = QLoggingCategory::defaultCategory()->categoryName();
    logSubscriber.installMessageHandle(std::bind(&LogCollector::onNewLog, this, std::placeholders::_1));
}

LogCollector::~LogCollector()
{
    logSubscriber.stopListenMessage();
}

void LogCollector::init(ConfigArray *addrToBeListened)
{
    try
    {
        for (int i = 0; i < addrToBeListened->configCount(); i++)
        {
            logSubscriber.subscribe(addrToBeListened->at(i).toString());
        }
        logSubscriber.startListenMessage();
    }
    catch (std::exception &ex)
    {
        qFatal(ex.what());
    }
}
